/*
 * 
 * @author: Rahul
 * */

/*
 * 
 * @author: Rahul
 * */

exports.FETCH_HOME_SLIDER_IMAGE   = 'FETCH_HOME_SLIDER_IMAGE';
exports.HOME_SLIDER_IMAGE_SUCCESS = 'HOME_SLIDER_IMAGE_SUCCESS';
exports.HOME_SLIDER_IMAGE_FAILURE   = 'HOME_SLIDER_IMAGE_FAILURE';
exports.FETCH_VENDOR_LIST   = 'FETCH_VENDOR_LIST';

exports.USER_NAME = 'USER_NAME';
exports.USER_EMAIL = 'USER_EMAIL';
exports.USER_MOBILE = 'USER_MOBILE';
exports.USER_PROFILE_PIC = 'USER_PROFILE_PIC';
exports.IS_LOG_IN = 'IS_LOG_IN';
exports.USER_TYPE = 'USER_TYPE';
exports.VENDOR = 'VENDOR';
exports.CUSTOMER = 'CUSTOMER';
exports.USER_ID = 'USER_ID';
exports.VENDOR_ID = 'VENDOR_ID';
exports.COMPANY_LOGO = 'COMPANY_LOGO';

// export default { FETCH_HOME_SLIDER_IMAGE, HOME_SLIDER_IMAGE_FAILURE, FETCH_VENDOR_LIST, HOME_SLIDER_IMAGE_SUCCESS };